# Generated by Django 6.0.4 on 2026-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reader/covers/')),
                ('folder_name', models.CharField(help_text='Folder containing page images', max_length=255, unique=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('curriculum', 'Curriculum'), ('novel', 'Novel'), ('story', 'Story'), ('other', 'Other')], default='book', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='Original object id', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
