# Generated by Django 6.0.4 on 2026-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readerbook',
            options={'ordering': ['title'], 'verbose_name': 'Reader Book', 'verbose_name_plural': 'Reader Books'},
        ),
        migrations.AddField(
            model_name='readerbook',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reader/pdfs/'),
        ),
    ]
