# Generated by Django 6.0.4 on 2026-06-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('badges_earned', models.PositiveIntegerField(default=0)),
                ('current_level_label', models.CharField(default='A1', max_length=50)),
                ('level_progress', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.student')),
            ],
        ),
    ]
