# Generated by Django 6.0.4 on 2026-06-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logins', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
