# Generated by Django 6.0.4 on 2026-06-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_series/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Book Series',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='curriculum_series/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Curriculum Series',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_embed_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LevelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='level_tests/')),
                ('pass_score', models.IntegerField(default=60)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News title in English', max_length=255)),
                ('title_ar', models.CharField(help_text='News title in Arabic', max_length=255)),
                ('content', models.TextField(help_text='News content in English')),
                ('content_ar', models.TextField(help_text='News content in Arabic')),
                ('image', models.ImageField(blank=True, help_text='Optional news image', null=True, upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title in English', max_length=255)),
                ('title_ar', models.CharField(help_text='Course title in Arabic', max_length=255)),
                ('description', models.TextField(help_text='Course description in English')),
                ('description_ar', models.TextField(help_text='Course description in Arabic')),
                ('image', models.ImageField(blank=True, help_text='Course cover image', null=True, upload_to='online_courses/')),
                ('start_date', models.DateField(help_text='Course start date')),
                ('time', models.TimeField(help_text='Course daily/weekly time')),
                ('duration_weeks', models.IntegerField(default=4, help_text='Duration in weeks')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Course price (0 for free)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Is course currently open for registration?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image + Text'), ('video', 'Video + Text'), ('audio', 'Audio + Text')], default='text', max_length=10)),
                ('answer_type', models.CharField(choices=[('choices', 'Multiple Choice (Single Select)'), ('multi_choices', 'Multiple Selection (Checkboxes)'), ('text', 'Text Answer')], default='choices', max_length=15)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL for video questions', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Video file for video questions', null=True, upload_to='quiz_video/')),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for audio questions', null=True, upload_to='quiz_audio/')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='quiz_images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('order', models.IntegerField(default=0)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='courses.bookseries')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='levels/')),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='curriculum_audio/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='curriculum_covers/')),
                ('order', models.IntegerField(default=0)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculums', to='courses.curriculumseries')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LevelTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image + Text'), ('video', 'Video + Text'), ('audio', 'Audio + Text')], default='text', max_length=10)),
                ('answer_type', models.CharField(choices=[('choices', 'Multiple Choice (Single Select)'), ('multi_choices', 'Multiple Selection (Checkboxes)'), ('text', 'Text Answer')], default='choices', max_length=15)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL for video questions')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='level_test_video/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='level_test_audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='level_test_images/')),
                ('time_limit_seconds', models.IntegerField(default=60, help_text='Time limit for this question in seconds')),
                ('score', models.IntegerField(default=1, help_text='Score for this question')),
                ('order', models.IntegerField(default=0)),
                ('level_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.leveltest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LevelTestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.leveltestquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lecture title in English', max_length=255)),
                ('title_ar', models.CharField(help_text='Lecture title in Arabic', max_length=255)),
                ('meeting_url', models.URLField(help_text='Zoom or Meet link')),
                ('date', models.DateField(help_text='Lecture date')),
                ('time', models.TimeField(help_text='Lecture time')),
                ('order', models.IntegerField(default=0, help_text='Lecture order')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.onlinecourse')),
            ],
            options={
                'ordering': ['date', 'time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pass_score', models.IntegerField(default=60, help_text='Minimum percentage to pass (0-100)')),
                ('duration', models.IntegerField(default=10, help_text='Duration in minutes')),
                ('random_questions_count', models.IntegerField(blank=True, help_text='Number of random questions to select. If blank, all questions are shown.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.courselevel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentLevelTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('level_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.leveltest')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLevelTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('awarded_score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.leveltestquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.leveltestchoice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='+', to='courses.leveltestchoice')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.studentleveltestprogress')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Progress',
                'verbose_name_plural': 'Quiz Progress Records',
                'unique_together': {('student_id', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
        ),
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress Records',
                'unique_together': {('student_id', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_students', to='courses.choice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='multi_selected_by_students', to='courses.choice')),
                ('quiz_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.studentquizprogress')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'unique_together': {('student_id', 'question')},
            },
        ),
    ]
