# Generated by Django 6.0.4 on 2026-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltestquestion',
            name='correct_text_answer',
            field=models.CharField(blank=True, help_text='The correct text answer (if answer type is Text Answer)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, help_text='The correct text answer (if answer type is Text Answer)', max_length=500, null=True),
        ),
    ]
