# Generated by Django 6.0.4 on 2026-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_leveltestquestion_correct_text_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizprogress',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentquizprogress',
            name='retry_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
