# Generated by Django 6.0.4 on 2026-06-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentstats'),
        ('courses', '0003_studentquizprogress_failed_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(help_text='The word in English', max_length=100)),
                ('translation_ar', models.CharField(help_text='Translation in Arabic', max_length=200)),
                ('example_sentence', models.TextField(blank=True, help_text='Optional example sentence', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one should be active ideally')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Words of the Day',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-last_accessed'],
            },
        ),
    ]
