# Generated by Django 6.0.4 on 2026-06-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_badge_completedlesson_studentbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='series',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookSeries',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='CurriculumSeries',
        ),
    ]
